application:
  name: addressbook-jenkins-maven-project
  version: 1.0.0

server:
  port: 8080

spring:
  application:
    name: addressbook-jenkins-maven-project

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
